load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_binary", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_binary(
    name = "dcxctl",
    srcs = ["src/main.rs"],
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    deps = ["//crates/dcx-core:dcx_core"] + all_crate_deps(normal = True),
)

rust_binary(
    name = "dcxctl_live_discovery",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["live-discovery"],
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    target_compatible_with = select({
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//crates/dcx-core:dcx_core",
        "//crates/dcx-darwin-tty:dcx_darwin_tty",
        "//crates/dcx-transport:dcx_transport",
        "@crates//:serde",
        "@crates//:sha2",
    ] + all_crate_deps(normal = True),
)

rust_test(
    name = "live_discovery_unit_tests",
    size = "small",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["live-discovery"],
    crate_root = "src/main.rs",
    edition = "2024",
    proc_macro_deps = all_crate_deps(proc_macro = True),
    target_compatible_with = select({
        "@platforms//os:macos": [],
        "//conditions:default": ["@platforms//:incompatible"],
    }),
    deps = [
        "//crates/dcx-core:dcx_core",
        "//crates/dcx-darwin-tty:dcx_darwin_tty",
        "//crates/dcx-transport:dcx_transport",
        "@crates//:serde",
        "@crates//:sha2",
    ] + all_crate_deps(normal = True),
)
