load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "dcx_transport",
    srcs = glob(["src/**/*.rs"]),
    crate_name = "dcx_transport",
    edition = "2024",
    deps = ["//crates/dcx-core:dcx_core"] + all_crate_deps(normal = True),
)

rust_test(
    name = "unit_tests",
    size = "small",
    crate = ":dcx_transport",
)

rust_test(
    name = "robustness",
    size = "small",
    srcs = ["tests/robustness.rs"],
    edition = "2024",
    deps = [
        ":dcx_transport",
        "//crates/dcx-core:dcx_core",
    ] + all_crate_deps(normal = True),
)

test_suite(
    name = "all_tests",
    tests = [
        ":robustness",
        ":unit_tests",
    ],
)
